"""원티드 접근 경로 진단 스크립트 (수집 파이프라인과 무관한 조사 전용).

2026-07-16부터 GitHub Actions 러너에서 원티드 검색 페이지가 CloudFront WAF에
전부 차단됐다(로컬 IP는 정상). 차단이 'IP 단위'인지 '헤드리스 브라우저 지문 단위'인지
확인하려고, 러너에서 아래 3가지를 각각 찔러본다.

  A. 검색 페이지 HTML (requests) — 지금 스크래퍼가 Playwright로 여는 그 주소
  B. 검색 API   /api/chaos/search/v1/position
  C. 상세 API   /api/chaos/jobs/v1/{id}/details

B·C가 통과하면 스크래퍼를 브라우저 없는 API 방식으로 교체할 수 있다.
결과만 출력하고 항상 정상 종료한다(로그를 읽는 게 목적).
"""
import sys
from urllib.parse import quote

import requests

KEYWORDS = ["게임 회계", "게임 세무", "게임 재무", "게임 자금"]
SAMPLE_JOB_ID = 355934  # 현재 유일한 활성 원티드 공고(데브즈유나이티드게임즈)

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")


def _headers(referer):
    return {
        "User-Agent": UA,
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "ko-KR,ko;q=0.9",
        "Referer": referer,
    }


def _is_waf_block(resp):
    """CloudFront WAF 차단 응답인지 판별 (HTML 차단 페이지가 200으로 올 수도 있음)"""
    if resp.status_code in (403, 405, 429):
        return True
    head = resp.text[:1000].lower()
    return "satisfied" in head or "generated by cloudfront" in head


def probe_search_html():
    print("\n===== A. 검색 페이지 HTML (requests) =====")
    for kw in KEYWORDS:
        url = "https://www.wanted.co.kr/search?query=" + quote(kw)
        try:
            r = requests.get(url, headers={"User-Agent": UA, "Accept-Language": "ko-KR,ko;q=0.9"}, timeout=20)
            blocked = _is_waf_block(r)
            wd_count = r.text.count("/wd/")
            print(f"  [{kw}] HTTP {r.status_code} len={len(r.text)} "
                  f"WAF차단={blocked} '/wd/'등장={wd_count}")
            if blocked:
                # 차단 사유를 구분하려면 본문 전체가 필요하다. CloudFront는 지역 차단이면
                # '...configured to block access from your country', WAF 룰이면
                # '...not authorized' / 'Request blocked' 식으로 문구가 다르다.
                print(f"      차단 응답 전문: {r.text!r}")
                print(f"      응답 헤더: {dict(r.headers)}")
        except Exception as e:
            print(f"  [{kw}] 예외: {e}")


def probe_search_api():
    print("\n===== B. 검색 API /api/chaos/search/v1/position =====")
    ok_any = False
    for kw in KEYWORDS:
        url = "https://www.wanted.co.kr/api/chaos/search/v1/position"
        params = {
            "query": kw, "country": "kr", "years": "-1", "locations": "all",
            "sort": "job.recommend_order", "limit": 20, "offset": 0,
        }
        try:
            r = requests.get(url, headers=_headers("https://www.wanted.co.kr/search?query=" + quote(kw)),
                             params=params, timeout=20)
            blocked = _is_waf_block(r)
            if r.status_code == 200 and not blocked:
                data = r.json().get("data") or []
                ok_any = True
                print(f"  [{kw}] HTTP 200 공고 {len(data)}건 "
                      f"→ {[(d.get('id'), d.get('position')) for d in data]}")
            else:
                print(f"  [{kw}] HTTP {r.status_code} WAF차단={blocked} 본문: {r.text[:200]!r}")
        except Exception as e:
            print(f"  [{kw}] 예외: {e}")
    return ok_any


def probe_detail_api():
    print("\n===== C. 상세 API /api/chaos/jobs/v1/{id}/details =====")
    url = f"https://www.wanted.co.kr/api/chaos/jobs/v1/{SAMPLE_JOB_ID}/details"
    try:
        r = requests.get(url, headers=_headers(f"https://www.wanted.co.kr/wd/{SAMPLE_JOB_ID}"), timeout=20)
        blocked = _is_waf_block(r)
        if r.status_code == 200 and not blocked:
            job = r.json().get("job") or {}
            detail = job.get("detail") or {}
            company = (job.get("company") or {}).get("name")
            print(f"  HTTP 200 회사={company} 상태={job.get('status')} 마감={job.get('due_time')} "
                  f"경력={job.get('annual_from')}~{job.get('annual_to')}")
            print(f"  detail 필드={list(detail.keys())} "
                  f"본문길이={sum(len(v) for v in detail.values() if isinstance(v, str))}자")
            return True
        print(f"  HTTP {r.status_code} WAF차단={blocked} 본문: {r.text[:200]!r}")
    except Exception as e:
        print(f"  예외: {e}")
    return False


if __name__ == "__main__":
    print(f"[진단] 원티드 접근 경로 점검 시작 (python {sys.version.split()[0]})")
    probe_search_html()
    search_ok = probe_search_api()
    detail_ok = probe_detail_api()
    print("\n===== 결론 =====")
    print(f"  검색 API 사용 가능: {search_ok}")
    print(f"  상세 API 사용 가능: {detail_ok}")
    if search_ok and detail_ok:
        print("  → 러너에서 API 경로가 살아 있다. 브라우저 없는 API 방식으로 교체 가능.")
    else:
        print("  → API도 차단됨. IP 단위 차단으로 보이며 코드 교체로는 해결 불가.")
